#229 change the image build process so that docker image can be launched without a project.
dbflute/dbflute-intro pull request #292
Opened 2021-04-17 09:43 UTC by ryo-chin

- if the jar file is not exist, it can be achieved by downloading it.

2021-04-17 09:45 UTC, ryo-chin commented on docker/dbflute-intro/Dockerfile
> +# TODO hakiba: make sure need it.
TODO: delete if not needs

2021-04-18 00:13 UTC, EgumaYuto requested changes

2021-04-20 00:37 UTC, ryo-chin commented on docker/dbflute-intro/Dockerfile
> +COPY version.txt /scripts/version.txt
Sorry, I can't do it because the shell file disappears when I mount it on /app

2021-04-20 00:52 UTC, ryo-chin commented on docker/dbflute-intro/scripts/startup.sh
> +cd /app
change working directory to /app  👍

2021-04-20 00:52 UTC, ryo-chin commented on docker/dbflute-intro/Dockerfile
> +CMD ["sh", "scripts/startup.sh"]
change to use ENTRYPOINT 👍

2021-05-01 04:12 UTC, EgumaYuto commented on scripts/docker-build.sh
> +rm docker/dbflute-intro/dbflute-intro.jar
外部からファイルをコピーして上げたりするのではなくて、
できるだけ Dockerfile 一枚でビルドができるようにしてあげてください
Dockerfileどの範囲の環境（ディレクトリ）を固めたのかというのを表せる配置にしておいてほしいです

あと、このままだと、このスクリプト経由でしかビルドできず、かつpushも同時にやってしまうので扱いづらいです

2021-05-01 05:59 UTC, ryo-chin commented on scripts/docker-build.sh
> +rm docker/dbflute-intro/dbflute-intro.jar
Dockerfileとその他諸々のファイルをrootに移動して、Docker内部の構造と同じになるようにしました！

2021-05-01 06:25 UTC, EgumaYuto approved these changes
細かめなので Approve しておきます

2021-05-01 06:25 UTC, EgumaYuto commented on entrypoint.sh
> +cp /dbflute-intro.jar /app/dbflute-intro.jar
細かいけど、コピーするときは起動に必要な jar ファイルがなければでいいはず 🤔

2021-05-01 07:28 UTC, ryo-chin commented on entrypoint.sh
> +cp /dbflute-intro.jar /app/dbflute-intro.jar
ファイルの存在判定処理追加しておきます！

2021-05-01 08:52 UTC, merged